#!/usr/bin/env bash

check_factor()
{
    if [ $# -ne 3 ]; then
        args=("$@")
        max1=1
        max2=1

        for a in ${args[*]}; do
            if [ $a -gt $max1 ]; then
                max2=$max1
                max1=$a
            elif [ $a -gt $max2 ]; then
                max2=$a
            fi
        done
    else
        max1=$2
        max2=$3
    fi

    num=$(echo "$1" | tr ':' '=')

    if [ $max2 -gt $max1 ]; then
        numcp=$max1
        max1=$max2
        max2=$numcp
    fi

    echo "$num$max1*$max2"
}

